#!/usr/bin/env python3
"""
mpra_empirical_analysis.py — Empirical MPRA Fiber-seq Footprint Analysis (v0.1.0)

An empirical-first approach to detecting variant effects on protein-DNA
interactions from Fiber-seq MPRA data.

CORE APPROACH:
  The primary test statistic is the raw occupancy difference:
    Δ_obs(pos) = variant_occ(pos) - WT_occ(pos)

  Significance is assessed by comparing Δ_obs to an empirical null
  distribution generated by subsampling WT reads at variant-like coverage
  (NC-matched to the ground truth WT NC distribution).

  Cluster detection uses adaptive thresholding: positions where |Δ_obs|
  exceeds the per-position (1-α) quantile of |Δ_null| are merged into
  clusters. Cluster significance is assessed by comparing the cluster's
  sum(|Δ|) to the null cluster-sum distribution.

ANALYSIS PHASES:
  1. Parse & Setup:     BAM parsing, NC distributions, filter grid
  2. Chromatin Shift:   WT vs variant NC distribution comparison
  3. Null Calibration:  Empirical null at primary coverage + coverage grid
  4. Variant Testing:   Position-level and cluster-level significance
  5. Filter Optimization: Detection metrics across NC filter grid
  6. Power Analysis:    Detection rate vs coverage depth

OUTPUTS:
  - HDF5 file with full results, null distributions, and cluster calls
  - Multi-page diagnostic PDF
  - Jupyter notebook template for interactive exploration

Author: Ben / Stergachis Lab, University of Washington
"""

import argparse
import array as arr_module
import json
import logging
import multiprocessing
import os
import struct
import sys
import time
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime
from multiprocessing import shared_memory

import h5py
import numpy as np
import pysam
from scipy import ndimage, stats as scipy_stats

try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    def tqdm(iterable, **kwargs):
        return iterable

VERSION = "0.1.0"

# ============================================================================
# Constants
# ============================================================================

FOOTPRINT_BINS = {
    'sub_TF': (10, 19, 'sub-TF_10-19bp'),
    'TF':     (20, 40, 'TF_20-40bp'),
    'PIC':    (41, 80, 'PIC_41-80bp'),
    'NUC':    (81, np.inf, 'Nucleosome_81plusbp'),
}

CLUSTER_WIDTH_RANGES = {
    'sub-TF_10-19bp':      (5, 30),
    'TF_20-40bp':          (10, 60),
    'PIC_41-80bp':         (25, 100),
    'Nucleosome_81plusbp':  (50, 200),
}

TAG_NUC_COUNT = 'nc'
TAG_PROMOTER_VARIANT = 'PV'
TAG_VARIANT_COUNT = 'VC'
TAG_FP_STARTS = 'ns'
TAG_FP_LENGTHS = 'nl'
TAG_FP_QUAL = 'nq'


# ============================================================================
# Utilities
# ============================================================================

def setup_logging(verbose=False):
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S')


def safe_hdf5_name(name):
    return (name.replace(' ', '_').replace('(', '').replace(')', '')
                .replace('+', 'plus').replace('>', 'to').replace(':', '_'))


def benjamini_hochberg(p_values):
    """Apply Benjamini-Hochberg FDR correction."""
    p = np.asarray(p_values, dtype=np.float64)
    n = len(p)
    if n == 0:
        return np.array([], dtype=np.float64)
    order = np.argsort(p)
    ranks = np.empty_like(order)
    ranks[order] = np.arange(1, n + 1)
    q = p * n / ranks
    sorted_q = q[order]
    for i in range(n - 2, -1, -1):
        sorted_q[i] = min(sorted_q[i], sorted_q[i + 1])
    q[order] = sorted_q
    return np.minimum(q, 1.0)


# ============================================================================
# BAM Tag Parsing
# ============================================================================

def parse_tag_array(tag_value):
    """Parse a BAM tag value into a list of integers."""
    if isinstance(tag_value, (list, tuple, np.ndarray)):
        return [int(x) for x in tag_value]
    if isinstance(tag_value, arr_module.array):
        return [int(x) for x in tag_value]
    if isinstance(tag_value, (bytes, bytearray)):
        n = len(tag_value)
        if n == 0:
            return []
        if n % 4 == 0:
            vals = list(struct.unpack(f'<{n // 4}I', tag_value))
            if all(0 <= v < 100000 for v in vals):
                return vals
        if n % 2 == 0:
            vals = list(struct.unpack(f'<{n // 2}H', tag_value))
            if all(0 <= v < 100000 for v in vals):
                return vals
        if n % 4 == 0:
            return list(struct.unpack(f'<{n // 4}i', tag_value))
        raise ValueError(f'Cannot parse bytes tag of length {n}')
    if isinstance(tag_value, str):
        return [int(x) for x in tag_value.split(',') if x.strip()]
    return [int(tag_value)]


def parse_variant_tag(pv_value):
    """Parse the PV (promoter variant) tag."""
    if pv_value == "WT":
        return ["WT"]
    try:
        variants = json.loads(pv_value)
        return variants if isinstance(variants, list) else [str(variants)]
    except (json.JSONDecodeError, TypeError):
        return [str(pv_value)]


# ============================================================================
# ReadData: Numpy-backed storage with pre-computed coverage matrices
# ============================================================================

class ReadData:
    """
    Compact, numpy-backed storage for parsed Fiber-seq reads.

    All per-read data is stored as parallel numpy arrays. Coverage matrices
    (uint8, n_reads x ref_length per bin) enable O(1) occupancy computation:
        occupancy = coverage_matrices[bin][read_indices].mean(axis=0)
    """

    def __init__(self, ref_length, bin_labels):
        self.ref_length = ref_length
        self.bin_labels = list(bin_labels)
        self.n_bins = len(bin_labels)
        self.bin_to_idx = {label: i for i, label in enumerate(bin_labels)}

        self._nuc_counts = []
        self._variant_ids = []
        self._variant_counts = []
        self._coverage_rows = {label: [] for label in bin_labels}

        self.n_reads = 0
        self._frozen = False

        self.nuc_counts = None
        self.variant_ids = None
        self.variant_counts = None
        self.coverage_matrices = None
        self.wt_indices = None
        self.variant_indices = None

    def add_read(self, nuc_count, variant_id, variant_count, footprints,
                 ref_length):
        assert not self._frozen
        self._nuc_counts.append(nuc_count if nuc_count is not None else -1)
        self._variant_ids.append(variant_id)
        self._variant_counts.append(variant_count)

        coverage = {label: np.zeros(ref_length, dtype=np.uint8)
                    for label in self.bin_labels}
        for bin_label, ref_positions, quality, size in footprints:
            if bin_label not in self.bin_to_idx:
                continue
            pos_arr = np.array(list(ref_positions), dtype=np.int32)
            if len(pos_arr) > 0:
                coverage[bin_label][pos_arr] = 1
        for label in self.bin_labels:
            self._coverage_rows[label].append(coverage[label])

        self.n_reads += 1

    def freeze(self):
        if self._frozen:
            return
        logging.info(f"Freezing ReadData: {self.n_reads:,} reads x "
                     f"{self.ref_length} bp x {self.n_bins} bins")
        t0 = time.time()

        self.nuc_counts = np.array(self._nuc_counts, dtype=np.int32)
        self.variant_ids = np.array(self._variant_ids, dtype=object)
        self.variant_counts = np.array(self._variant_counts, dtype=np.int32)

        self.coverage_matrices = {}
        for label in self.bin_labels:
            if self._coverage_rows[label]:
                self.coverage_matrices[label] = np.vstack(
                    self._coverage_rows[label])
            else:
                self.coverage_matrices[label] = np.zeros(
                    (0, self.ref_length), dtype=np.uint8)
            self._coverage_rows[label] = None

        self.wt_indices = np.where(self.variant_ids == 'WT')[0]
        unique_variants = set(self.variant_ids) - {'WT'}
        self.variant_indices = {
            vid: np.where(self.variant_ids == vid)[0]
            for vid in unique_variants
        }

        total_bytes = sum(m.nbytes for m in self.coverage_matrices.values())
        logging.info(f"  Coverage matrices: {total_bytes / 1e6:.1f} MB")
        logging.info(f"  WT reads: {len(self.wt_indices):,}")
        for vid, idx in self.variant_indices.items():
            logging.info(f"  Variant '{vid}': {len(idx):,}")
        logging.info(f"  Freeze time: {time.time() - t0:.2f}s")

        self._frozen = True
        self._nuc_counts = None
        self._variant_ids = None
        self._variant_counts = None

    def get_indices_filtered(self, indices, min_nuc=None, max_nuc=None):
        if min_nuc is None and max_nuc is None:
            return indices
        mask = np.ones(len(indices), dtype=bool)
        nc = self.nuc_counts[indices]
        if min_nuc is not None:
            mask &= (nc >= 0) & (nc >= min_nuc)
        if max_nuc is not None:
            mask &= (nc >= 0) & (nc <= max_nuc)
        return indices[mask]

    def occupancy(self, indices, bin_label):
        if len(indices) == 0:
            return np.zeros(self.ref_length, dtype=np.float64)
        return self.coverage_matrices[bin_label][indices].mean(axis=0)

    def occupancy_all_bins(self, indices):
        return {label: self.occupancy(indices, label)
                for label in self.bin_labels}


# ============================================================================
# BAM Parsing
# ============================================================================

def parse_target_region(region_str):
    if region_str is None:
        return None, None, None
    if ':' in region_str:
        chrom, coords = region_str.split(':', 1)
        parts = coords.split('-')
        if len(parts) != 2:
            raise ValueError(f"Invalid target region: {region_str}")
        return chrom, int(parts[0]), int(parts[1])
    return region_str, None, None


def resolve_target_chrom(ref_info, target_chrom):
    if target_chrom is not None:
        if target_chrom not in ref_info:
            raise ValueError(
                f"'{target_chrom}' not in BAM. "
                f"Available: {', '.join(ref_info)}")
        return target_chrom, ref_info[target_chrom]
    if len(ref_info) == 1:
        name = list(ref_info.keys())[0]
        return name, ref_info[name]
    raise ValueError(
        f"Multiple refs: {', '.join(ref_info)}. Use --target-region.")


def build_query_to_ref_map(aligned_pairs):
    return {qpos: rpos for qpos, rpos in aligned_pairs
            if qpos is not None and rpos is not None}


def convert_footprints(fp_starts, fp_lengths, fp_quals, q2r_map,
                       ref_length, size_bins):
    footprints = []
    for i, (fp_start, fp_len) in enumerate(zip(fp_starts, fp_lengths)):
        bin_label = None
        for min_s, max_s, label in size_bins:
            if min_s <= fp_len <= max_s:
                bin_label = label
                break
        if bin_label is None:
            continue
        qual = (fp_quals[i] if fp_quals is not None and i < len(fp_quals)
                else None)
        ref_positions = set()
        for qpos in range(fp_start, fp_start + fp_len):
            rpos = q2r_map.get(qpos)
            if rpos is not None and 0 <= rpos < ref_length:
                ref_positions.add(rpos)
        if not ref_positions:
            continue
        footprints.append((bin_label, ref_positions, qual, fp_len))
    return footprints


def parse_bam(bam_path, size_bins, bin_labels, target_chrom=None):
    stats = {'total': 0, 'unmapped': 0, 'missing_pv_vc': 0,
             'missing_fp_tags': 0, 'no_footprints': 0, 'off_target': 0,
             'parsed': 0}
    bin_tuples = [(b[0], b[1], b[2]) for b in size_bins]

    with pysam.AlignmentFile(bam_path, 'rb') as bam:
        ref_info = {sq['SN']: sq['LN'] for sq in bam.header['SQ']}
        logging.info(f"References in BAM: {ref_info}")
        ref_name, ref_length = resolve_target_chrom(ref_info, target_chrom)
        logging.info(f"Using reference: {ref_name} ({ref_length:,} bp)")

        rd = ReadData(ref_length, bin_labels)
        total_reads = None
        try:
            total_reads = sum(
                s.mapped + s.unmapped
                for s in bam.get_index_statistics())
        except (ValueError, AttributeError):
            pass

        for read in tqdm(bam, total=total_reads, desc="Parsing BAM",
                         unit=" reads", disable=not HAS_TQDM):
            stats['total'] += 1
            if (read.is_unmapped or read.is_secondary
                    or read.is_supplementary):
                stats['unmapped'] += 1
                continue
            if read.reference_name != ref_name:
                stats['off_target'] += 1
                continue
            try:
                pv_value = read.get_tag(TAG_PROMOTER_VARIANT)
                vc_value = read.get_tag(TAG_VARIANT_COUNT)
            except KeyError:
                stats['missing_pv_vc'] += 1
                continue
            try:
                nuc_count = int(read.get_tag(TAG_NUC_COUNT))
            except KeyError:
                nuc_count = None
            try:
                fp_starts = parse_tag_array(read.get_tag(TAG_FP_STARTS))
                fp_lengths = parse_tag_array(read.get_tag(TAG_FP_LENGTHS))
            except KeyError:
                stats['missing_fp_tags'] += 1
                continue
            fp_quals = None
            try:
                fp_quals = parse_tag_array(read.get_tag(TAG_FP_QUAL))
            except KeyError:
                pass
            if len(fp_starts) == 0:
                stats['no_footprints'] += 1

            q2r = build_query_to_ref_map(
                read.get_aligned_pairs(matches_only=False))
            footprints = convert_footprints(
                fp_starts, fp_lengths, fp_quals, q2r,
                ref_length, bin_tuples)

            if pv_value == "WT" or vc_value == 0:
                variant_id = "WT"
            else:
                variants = parse_variant_tag(pv_value)
                variant_id = (variants[0] if len(variants) == 1
                              else json.dumps(variants))

            rd.add_read(nuc_count, variant_id, int(vc_value),
                        footprints, ref_length)
            stats['parsed'] += 1

    logging.info(f"Parsed {stats['parsed']:,} reads from "
                 f"{stats['total']:,} total")
    rd.freeze()
    return rd, ref_length, ref_name, stats


# ============================================================================
# Ground Truth NC Distribution & NC-Matched Subsampling
# ============================================================================

def compute_ground_truth_nc(rd, wt_idx, min_nuc=None, max_nuc=None):
    wt_f = rd.get_indices_filtered(wt_idx, min_nuc=min_nuc, max_nuc=max_nuc)
    nc = rd.nuc_counts[wt_f]
    nc_valid = nc[nc >= 0]
    if len(nc_valid) == 0:
        logging.warning("No valid NC values in filtered WT reads!")
        return None
    unique_nc, counts = np.unique(nc_valid, return_counts=True)
    fracs = counts.astype(np.float64) / counts.sum()
    logging.info(f"  Ground truth NC: {len(wt_f):,} reads, "
                 f"range=[{unique_nc[0]}, {unique_nc[-1]}], "
                 f"mean={np.mean(nc_valid):.1f}")
    return {
        'nc_vals': unique_nc, 'nc_fracs': fracs,
        'n_reads': len(wt_f), 'min_nuc': min_nuc, 'max_nuc': max_nuc,
    }


def nc_matched_subsample(indices, nuc_counts, target_nc_fracs,
                         target_nc_vals, rng, replace=False):
    """Subsample read indices to match a target NC distribution."""
    nc = nuc_counts[indices]
    n_total = len(indices)
    available = {}
    for nc_val in target_nc_vals:
        available[nc_val] = indices[nc == nc_val]

    if not replace:
        # Analytical max feasible N
        max_n = n_total
        for nc_val, frac in zip(target_nc_vals, target_nc_fracs):
            pool_size = len(available.get(nc_val, []))
            if frac > 1e-10 and pool_size > 0:
                max_n = min(max_n, int(pool_size / frac))
            elif frac > 1e-10:
                max_n = 0
        if max_n == 0:
            return indices, len(indices)

        draws = []
        for nc_val, frac in zip(target_nc_vals, target_nc_fracs):
            pool = available.get(nc_val, np.array([], dtype=int))
            n_take = max(1, int(round(frac * max_n)))
            n_take = min(n_take, len(pool))
            if n_take > 0:
                draws.append(rng.choice(pool, size=n_take, replace=False))
        if not draws:
            return indices, len(indices)
        subsampled = np.concatenate(draws)
        return subsampled, len(subsampled)
    else:
        size = n_total
        draws = []
        for nc_val, frac in zip(target_nc_vals, target_nc_fracs):
            pool = available.get(nc_val, np.array([], dtype=int))
            if len(pool) == 0:
                continue
            n_draw = max(1, int(round(frac * size)))
            draws.append(rng.choice(pool, size=n_draw, replace=True))
        if not draws:
            return rng.choice(indices, size=size, replace=True), size
        combined = np.concatenate(draws)
        if len(combined) >= size:
            return rng.permutation(combined)[:size], size
        pad = rng.choice(combined, size=size - len(combined), replace=True)
        return np.concatenate([combined, pad]), size


def _nc_matched_batch_draw(nc_draw_counts, wt_nc_pools, n_samples,
                           subsample_size, rng):
    """Generate n_samples sets of NC-matched read indices in batch."""
    all_draws = []
    for nc_val, n_draw in nc_draw_counts:
        pool = wt_nc_pools.get(nc_val)
        if pool is None or len(pool) == 0:
            continue
        drawn = rng.choice(pool, size=(n_samples, n_draw), replace=True)
        all_draws.append(drawn)

    if not all_draws:
        fallback_pool = max(wt_nc_pools.values(), key=len)
        return rng.choice(fallback_pool,
                          size=(n_samples, subsample_size), replace=True)
    combined = np.concatenate(all_draws, axis=1)
    if combined.shape[1] >= subsample_size:
        return combined[:, :subsample_size]
    pad_size = subsample_size - combined.shape[1]
    pad = rng.choice(combined.ravel(), size=(n_samples, pad_size),
                     replace=True)
    return np.concatenate([combined, pad], axis=1)


# ============================================================================
# Shared Memory Helpers
# ============================================================================

def create_shared_matrices(wt_mats, bin_labels):
    """Place WT coverage matrices into shared memory."""
    shm_info = {}
    shm_objects = []
    for label in bin_labels:
        mat = wt_mats[label]
        shm = shared_memory.SharedMemory(create=True, size=mat.nbytes)
        shared_arr = np.ndarray(mat.shape, dtype=mat.dtype, buffer=shm.buf)
        shared_arr[:] = mat[:]
        shm_info[label] = {
            'name': shm.name, 'shape': mat.shape,
            'dtype': str(mat.dtype),
        }
        shm_objects.append(shm)
    return shm_info, shm_objects


def load_shared_matrix(shm_meta):
    """Attach to existing shared memory matrix (worker side)."""
    shm = shared_memory.SharedMemory(name=shm_meta['name'], create=False)
    arr = np.ndarray(shm_meta['shape'],
                     dtype=np.dtype(shm_meta['dtype']),
                     buffer=shm.buf)
    return arr, shm


def cleanup_shared_memory(shm_objects):
    for shm in shm_objects:
        try:
            shm.close()
            shm.unlink()
        except Exception:
            pass


# ============================================================================
# Phase 2: Chromatin Shift Test
# ============================================================================

def chromatin_shift_test(rd, wt_idx, var_idx, min_nuc=None, max_nuc=None):
    """Test whether the variant shifts the NC distribution vs WT."""
    logging.info("=" * 60)
    logging.info("PHASE 2: Chromatin Shift Test")
    logging.info("=" * 60)

    wt_f = rd.get_indices_filtered(wt_idx, min_nuc=min_nuc, max_nuc=max_nuc)
    var_f = rd.get_indices_filtered(var_idx, min_nuc=min_nuc, max_nuc=max_nuc)
    wt_nc = rd.nuc_counts[wt_f]
    var_nc = rd.nuc_counts[var_f]
    wt_nc_valid = wt_nc[wt_nc >= 0]
    var_nc_valid = var_nc[var_nc >= 0]

    result = {'wt_n': len(wt_f), 'var_n': len(var_f),
              'wt_n_valid_nc': len(wt_nc_valid),
              'var_n_valid_nc': len(var_nc_valid)}

    if len(wt_nc_valid) == 0 or len(var_nc_valid) == 0:
        result['error'] = 'insufficient_nc_data'
        return result

    ks_stat, ks_pval = scipy_stats.ks_2samp(wt_nc_valid, var_nc_valid)
    delta_mean = float(np.mean(var_nc_valid) - np.mean(wt_nc_valid))
    delta_median = float(np.median(var_nc_valid) - np.median(wt_nc_valid))

    # Chi-squared on binned NC
    all_nc = np.concatenate([wt_nc_valid, var_nc_valid])
    unique_nc = np.unique(all_nc)
    wt_hist = np.array([np.sum(wt_nc_valid == nc) for nc in unique_nc])
    var_hist = np.array([np.sum(var_nc_valid == nc) for nc in unique_nc])
    total_wt, total_var = wt_hist.sum(), var_hist.sum()
    chi2, chi2_p = np.nan, np.nan
    if total_wt > 0 and total_var > 0:
        expected_var = wt_hist / total_wt * total_var
        valid_bins = expected_var >= 5
        if np.sum(valid_bins) >= 2:
            obs = var_hist[valid_bins]
            exp = expected_var[valid_bins]
            exp = exp * (obs.sum() / exp.sum())
            chi2, chi2_p = scipy_stats.chisquare(obs, exp)

    wt_u, wt_c = np.unique(wt_nc_valid, return_counts=True)
    var_u, var_c = np.unique(var_nc_valid, return_counts=True)

    result.update({
        'ks_stat': float(ks_stat), 'ks_pval': float(ks_pval),
        'delta_mean_nc': delta_mean, 'delta_median_nc': delta_median,
        'wt_mean_nc': float(np.mean(wt_nc_valid)),
        'var_mean_nc': float(np.mean(var_nc_valid)),
        'wt_median_nc': float(np.median(wt_nc_valid)),
        'var_median_nc': float(np.median(var_nc_valid)),
        'chi2_stat': float(chi2) if not np.isnan(chi2) else None,
        'chi2_pval': float(chi2_p) if not np.isnan(chi2_p) else None,
        'wt_nc_distribution': {int(k): int(v) for k, v in zip(wt_u, wt_c)},
        'var_nc_distribution': {int(k): int(v) for k, v in zip(var_u, var_c)},
    })

    logging.info(f"  WT: n={len(wt_f):,}, mean_nc={result['wt_mean_nc']:.1f}")
    logging.info(f"  Var: n={len(var_f):,}, mean_nc={result['var_mean_nc']:.1f}")
    logging.info(f"  KS stat={ks_stat:.4f}, p={ks_pval:.4e}")
    logging.info(f"  delta mean NC = {delta_mean:+.2f}")
    return result


# ============================================================================
# Cluster Detection (used by null calibration and variant testing)
# ============================================================================

def _detect_clusters_adaptive(abs_delta, threshold, gap_tolerance=2,
                              merge_distance=5, min_width=3):
    """Detect clusters of positions with |delta| above threshold."""
    sig = abs_delta > threshold
    n = len(sig)
    if not np.any(sig):
        return []

    # Gap bridging
    if gap_tolerance > 0:
        bridged = sig.copy()
        for i in range(n):
            if not sig[i]:
                left = np.any(sig[max(0, i - gap_tolerance):i])
                right = np.any(sig[i + 1:min(n, i + gap_tolerance + 1)])
                if left and right:
                    bridged[i] = True
        sig = bridged

    labeled, n_clusters = ndimage.label(sig)
    raw_clusters = []
    for c in range(1, n_clusters + 1):
        pos = np.where(labeled == c)[0]
        raw_clusters.append({'start': int(pos[0]), 'end': int(pos[-1])})

    # Merge nearby
    if len(raw_clusters) > 1:
        merged = [raw_clusters[0].copy()]
        for c in raw_clusters[1:]:
            if c['start'] - merged[-1]['end'] <= merge_distance:
                merged[-1]['end'] = c['end']
            else:
                merged.append(c.copy())
        raw_clusters = merged

    clusters = []
    for c in raw_clusters:
        s, e = c['start'], c['end']
        width = e - s + 1
        if width < min_width:
            continue
        region_delta = abs_delta[s:e + 1]
        clusters.append({
            'start': s, 'end': e, 'width': width,
            'sum_abs_delta': float(np.sum(region_delta)),
            'max_abs_delta': float(np.max(region_delta)),
            'mean_abs_delta': float(np.mean(region_delta)),
            'peak_position': s + int(np.argmax(region_delta)),
        })
    return clusters


def _detect_clusters_from_mask(sig_mask, abs_delta, signed_delta,
                               gap_tolerance=2, merge_distance=5,
                               min_width=3):
    """Detect clusters from a boolean significance mask, with direction."""
    n = len(sig_mask)
    if not np.any(sig_mask):
        return []

    if gap_tolerance > 0:
        bridged = sig_mask.copy()
        for i in range(n):
            if not sig_mask[i]:
                left = np.any(sig_mask[max(0, i - gap_tolerance):i])
                right = np.any(sig_mask[i + 1:min(n, i + gap_tolerance + 1)])
                if left and right:
                    bridged[i] = True
        sig_mask = bridged

    labeled, n_clusters = ndimage.label(sig_mask)
    raw_clusters = []
    for c in range(1, n_clusters + 1):
        pos = np.where(labeled == c)[0]
        raw_clusters.append({'start': int(pos[0]), 'end': int(pos[-1])})

    if len(raw_clusters) > 1:
        merged = [raw_clusters[0].copy()]
        for c in raw_clusters[1:]:
            if c['start'] - merged[-1]['end'] <= merge_distance:
                merged[-1]['end'] = c['end']
            else:
                merged.append(c.copy())
        raw_clusters = merged

    clusters = []
    for c in raw_clusters:
        s, e = c['start'], c['end']
        width = e - s + 1
        if width < min_width:
            continue
        region_abs = abs_delta[s:e + 1]
        region_signed = signed_delta[s:e + 1]
        peak_idx = np.argmax(region_abs)
        clusters.append({
            'start': s, 'end': e, 'width': width,
            'sum_abs_delta': float(np.sum(region_abs)),
            'max_abs_delta': float(np.max(region_abs)),
            'mean_abs_delta': float(np.mean(region_abs)),
            'mean_signed_delta': float(np.mean(region_signed)),
            'peak_position': s + int(peak_idx),
            'direction': 'loss' if np.mean(region_signed) < 0 else 'gain',
        })
    return clusters


# ============================================================================
# Phase 3: Null Calibration — Worker Function
# ============================================================================

def _null_worker_shared(args):
    """Worker for null iterations using shared memory matrices."""
    (it_seeds, shm_info, bin_labels, nc_draw_counts,
     wt_nc_pools_serialized, subsample_size, wt_occ_list,
     analysis_length, cluster_threshold_quantile, gap_tolerance,
     merge_distance, absolute_delta_threshold) = args

    n_iters = len(it_seeds)
    n_bins = len(bin_labels)

    # Attach to shared memory
    shared_mats = {}
    shm_handles = []
    for label in bin_labels:
        arr, shm = load_shared_matrix(shm_info[label])
        shared_mats[label] = arr
        shm_handles.append(shm)

    wt_nc_pools = {nc_val: pool for nc_val, pool in wt_nc_pools_serialized}
    wt_occ = {label: np.array(vals) for label, vals in zip(bin_labels, wt_occ_list)}

    delta_out = np.zeros((n_iters, n_bins, analysis_length), dtype=np.float32)
    cluster_stats = []

    for local_i, seed in enumerate(it_seeds):
        rng = np.random.default_rng(seed)
        pv_indices = _nc_matched_batch_draw(
            nc_draw_counts, wt_nc_pools, 1, subsample_size, rng)[0]

        iter_clusters = {}
        for bi, label in enumerate(bin_labels):
            pv_occ = shared_mats[label][pv_indices].mean(axis=0)
            delta = pv_occ - wt_occ[label]
            delta_out[local_i, bi, :] = delta.astype(np.float32)

            abs_delta = np.abs(delta)
            thresh = 0.0
            if cluster_threshold_quantile is not None:
                thresh = np.percentile(abs_delta,
                                       cluster_threshold_quantile * 100)
            if absolute_delta_threshold is not None:
                thresh = max(thresh, absolute_delta_threshold)

            clusters = _detect_clusters_adaptive(
                abs_delta, thresh, gap_tolerance, merge_distance)
            iter_clusters[label] = {
                'n_clusters': len(clusters),
                'max_cluster_sum': (max(c['sum_abs_delta'] for c in clusters)
                                    if clusters else 0.0),
                'cluster_sums': [c['sum_abs_delta'] for c in clusters],
                'cluster_widths': [c['width'] for c in clusters],
            }
        cluster_stats.append(iter_clusters)

    for shm in shm_handles:
        shm.close()

    return delta_out, cluster_stats


# ============================================================================
# Phase 3: Null Calibration — Main Entry Point
# ============================================================================

def run_null_calibration(rd, wt_idx, ground_truth_nc, coverage_level,
                         min_nuc=None, max_nuc=None,
                         n_iterations=500, random_seed=42,
                         analysis_region=None,
                         cluster_threshold_quantile=0.95,
                         absolute_delta_threshold=None,
                         gap_tolerance=2, merge_distance=5,
                         n_workers=1):
    """Generate empirical null distribution at a given coverage level.

    Returns full null delta matrix, null cluster statistics, and WT occupancy.
    """
    logging.info(f"  Null calibration: N={coverage_level}, "
                 f"iters={n_iterations}, workers={n_workers}")

    bin_labels = rd.bin_labels
    n_bins = len(bin_labels)

    if analysis_region is not None:
        a_start, a_end = analysis_region
    else:
        a_start, a_end = 0, rd.ref_length
    analysis_length = a_end - a_start

    wt_f = rd.get_indices_filtered(wt_idx, min_nuc=min_nuc, max_nuc=max_nuc)
    n_wt = len(wt_f)

    col_indices = np.arange(a_start, a_end)
    wt_mats = {l: rd.coverage_matrices[l][np.ix_(wt_f, col_indices)]
               for l in bin_labels}

    # Full WT occupancy: stable baseline
    wt_occ = {l: wt_mats[l].mean(axis=0).astype(np.float64) for l in bin_labels}

    # NC pools (local indices into wt_mats rows)
    wt_nc = rd.nuc_counts[wt_f]
    nc_vals = ground_truth_nc['nc_vals']
    nc_fracs = ground_truth_nc['nc_fracs']

    wt_nc_pools = {}
    for nc_val in nc_vals:
        pool = np.where(wt_nc == nc_val)[0]
        if len(pool) > 0:
            wt_nc_pools[nc_val] = pool
    wt_nc_pools_serialized = [(nc_val, pool)
                               for nc_val, pool in wt_nc_pools.items()]

    nc_draw_counts = []
    for nc_val, frac in zip(nc_vals, nc_fracs):
        n_draw = max(1, int(round(frac * coverage_level)))
        if nc_val in wt_nc_pools:
            nc_draw_counts.append((nc_val, n_draw))

    master_rng = np.random.default_rng(random_seed)
    all_seeds = master_rng.integers(0, 2**63, size=n_iterations)

    # Serialize WT occ as list for pickling
    wt_occ_list = [wt_occ[l].tolist() for l in bin_labels]

    null_delta = np.zeros((n_iterations, n_bins, analysis_length),
                          dtype=np.float32)
    all_cluster_stats = []

    if n_workers > 1 and n_iterations > 1:
        shm_info, shm_objects = create_shared_matrices(wt_mats, bin_labels)

        chunk_size = max(1, n_iterations // n_workers)
        seed_chunks = []
        for i in range(0, n_iterations, chunk_size):
            seed_chunks.append(all_seeds[i:i + chunk_size])

        worker_args = [
            (chunk, shm_info, bin_labels, nc_draw_counts,
             wt_nc_pools_serialized, coverage_level, wt_occ_list,
             analysis_length, cluster_threshold_quantile, gap_tolerance,
             merge_distance, absolute_delta_threshold)
            for chunk in seed_chunks
        ]

        try:
            with ProcessPoolExecutor(max_workers=n_workers) as executor:
                futures = {executor.submit(_null_worker_shared, wa): ci
                           for ci, wa in enumerate(worker_args)}
                results_by_chunk = {}
                for future in as_completed(futures):
                    ci = futures[future]
                    results_by_chunk[ci] = future.result()
                # Reassemble in order
                offset = 0
                for ci in range(len(seed_chunks)):
                    delta_chunk, cluster_chunk = results_by_chunk[ci]
                    n_chunk = delta_chunk.shape[0]
                    null_delta[offset:offset + n_chunk] = delta_chunk
                    all_cluster_stats.extend(cluster_chunk)
                    offset += n_chunk
        finally:
            cleanup_shared_memory(shm_objects)
    else:
        for it in tqdm(range(n_iterations), desc="    Null iters",
                       disable=not HAS_TQDM):
            rng = np.random.default_rng(all_seeds[it])
            pv_indices = _nc_matched_batch_draw(
                nc_draw_counts, wt_nc_pools, 1, coverage_level, rng)[0]

            iter_clusters = {}
            for bi, label in enumerate(bin_labels):
                pv_occ = wt_mats[label][pv_indices].mean(axis=0)
                delta = pv_occ - wt_occ[label]
                null_delta[it, bi, :] = delta.astype(np.float32)

                abs_d = np.abs(delta)
                thresh = 0.0
                if cluster_threshold_quantile is not None:
                    thresh = np.percentile(abs_d,
                                           cluster_threshold_quantile * 100)
                if absolute_delta_threshold is not None:
                    thresh = max(thresh, absolute_delta_threshold)
                clusters = _detect_clusters_adaptive(
                    abs_d, thresh, gap_tolerance, merge_distance)
                iter_clusters[label] = {
                    'n_clusters': len(clusters),
                    'max_cluster_sum': (max(c['sum_abs_delta'] for c in clusters)
                                        if clusters else 0.0),
                    'cluster_sums': [c['sum_abs_delta'] for c in clusters],
                    'cluster_widths': [c['width'] for c in clusters],
                }
            all_cluster_stats.append(iter_clusters)

    # Summarize
    results = {
        'null_delta': null_delta, 'wt_occ': wt_occ,
        'coverage_level': coverage_level, 'n_iterations': n_iterations,
        'analysis_region': (a_start, a_end),
        'analysis_length': analysis_length,
        'summary': {}, 'null_cluster_sums': {},
        'null_cluster_widths': {}, 'null_max_cluster_sums': {},
    }

    for bi, label in enumerate(bin_labels):
        delta_all = null_delta[:, bi, :]
        pos_mean = delta_all.mean(axis=0)
        pos_std = delta_all.std(axis=0)
        abs_delta_flat = np.abs(delta_all).flatten()

        all_sums, all_widths, max_sums = [], [], []
        for cs in all_cluster_stats:
            if label in cs:
                all_sums.extend(cs[label]['cluster_sums'])
                all_widths.extend(cs[label]['cluster_widths'])
                max_sums.append(cs[label]['max_cluster_sum'])

        results['summary'][label] = {
            'pos_null_mean': pos_mean,
            'pos_null_std': pos_std,
            'global_abs_delta_percentiles': {
                p: float(np.percentile(abs_delta_flat, p))
                for p in [50, 75, 90, 95, 99]
            },
            'fpr_delta_gt_0.01': float(np.mean(abs_delta_flat > 0.01)),
            'fpr_delta_gt_0.02': float(np.mean(abs_delta_flat > 0.02)),
            'fpr_delta_gt_0.05': float(np.mean(abs_delta_flat > 0.05)),
        }
        results['null_cluster_sums'][label] = np.array(all_sums, dtype=np.float32)
        results['null_cluster_widths'][label] = np.array(all_widths, dtype=np.int32)
        results['null_max_cluster_sums'][label] = np.array(max_sums, dtype=np.float32)

        mean_clust = np.mean([cs[label]['n_clusters']
                              for cs in all_cluster_stats if label in cs])
        logging.info(f"    {label}: null |delta| p95="
                     f"{results['summary'][label]['global_abs_delta_percentiles'][95]:.4f}, "
                     f"clusters/iter={mean_clust:.1f}")

    return results


# ============================================================================
# Phase 4: Variant Effect Testing
# ============================================================================

def variant_effect_test(rd, wt_idx, var_idx, ground_truth_nc, null_results,
                        promoter_start, promoter_end,
                        min_nuc=None, max_nuc=None, random_seed=42,
                        cluster_threshold_quantile=0.95,
                        absolute_delta_threshold=None,
                        gap_tolerance=2, merge_distance=5):
    """Test variant effect using empirical delta approach.

    Primary: position-level and cluster-level empirical p-values.
    Secondary: lightweight Z-scores from null delta mean/std.
    """
    logging.info("=" * 60)
    logging.info("PHASE 4: Variant Effect Testing")
    logging.info("=" * 60)

    bin_labels = rd.bin_labels
    a_start, a_end = null_results['analysis_region']
    analysis_length = null_results['analysis_length']

    prom_rel_start = max(0, promoter_start - a_start)
    prom_rel_end = min(analysis_length, promoter_end - a_start)
    prom_slice = slice(prom_rel_start, prom_rel_end)

    var_f = rd.get_indices_filtered(var_idx, min_nuc=min_nuc, max_nuc=max_nuc)
    nc_vals = ground_truth_nc['nc_vals']
    nc_fracs = ground_truth_nc['nc_fracs']
    rng = np.random.default_rng(random_seed)

    var_matched, var_n = nc_matched_subsample(
        var_f, rd.nuc_counts, nc_fracs, nc_vals, rng, replace=False)
    logging.info(f"  Variant: {len(var_f)} filtered, {var_n} NC-matched")

    col_indices = np.arange(a_start, a_end)
    wt_occ = null_results['wt_occ']

    results = {}
    for bi, label in enumerate(bin_labels):
        var_occ = rd.coverage_matrices[label][
            np.ix_(var_matched, col_indices)].mean(axis=0)

        delta_obs = var_occ - wt_occ[label]

        # Position-level empirical p-values
        null_delta = null_results['null_delta'][:, bi, :]
        n_null = null_delta.shape[0]
        abs_delta_obs = np.abs(delta_obs)
        abs_null = np.abs(null_delta)

        # Vectorized: count null iterations with |delta_null| >= |delta_obs|
        exceed_count = np.sum(
            abs_null >= abs_delta_obs[np.newaxis, :], axis=0)
        empirical_p = (exceed_count + 1) / (n_null + 1)

        # BH-FDR within promoter
        prom_p = empirical_p[prom_slice]
        prom_q = benjamini_hochberg(prom_p)
        q_values = np.ones(analysis_length)
        q_values[prom_slice] = prom_q

        # Lightweight Z-scores from null delta distribution
        null_mean = null_results['summary'][label]['pos_null_mean']
        null_std = null_results['summary'][label]['pos_null_std']
        null_std_floored = np.maximum(null_std, 1e-6)
        z_scores = (delta_obs - null_mean) / null_std_floored
        z_scores = np.nan_to_num(z_scores, nan=0.0)

        # Cluster detection: per-position null threshold
        pos_thresh = np.percentile(abs_null,
                                   cluster_threshold_quantile * 100, axis=0)
        sig_mask = abs_delta_obs > pos_thresh
        if absolute_delta_threshold is not None:
            sig_mask &= abs_delta_obs > absolute_delta_threshold

        clusters = _detect_clusters_from_mask(
            sig_mask, abs_delta_obs, delta_obs,
            gap_tolerance, merge_distance, min_width=3)

        # Cluster p-values
        null_csums = null_results['null_cluster_sums'].get(label, np.array([]))
        null_max_csums = null_results['null_max_cluster_sums'].get(
            label, np.array([]))

        for c in clusters:
            if len(null_csums) > 0:
                c['sum_p'] = max(
                    float(np.mean(null_csums >= c['sum_abs_delta'])),
                    1.0 / (len(null_csums) + 1))
            else:
                c['sum_p'] = np.nan
            if len(null_max_csums) > 0:
                c['max_sum_p'] = float(
                    np.mean(null_max_csums >= c['sum_abs_delta']))
            else:
                c['max_sum_p'] = np.nan

            expected = CLUSTER_WIDTH_RANGES.get(label, (3, 200))
            c['biologically_plausible'] = (
                expected[0] <= c['width'] <= expected[1])
            c['abs_start'] = c['start'] + a_start
            c['abs_end'] = c['end'] + a_start

        prom_clusters = [c for c in clusters
                         if c['end'] >= prom_rel_start
                         and c['start'] < prom_rel_end]
        sig_clusters = [c for c in prom_clusters
                        if c.get('sum_p', 1.0) < 0.05]

        # Compare empirical vs Z-score calls
        z_sig = np.abs(z_scores) > 2.0
        emp_sig = empirical_p < 0.05
        comparison = {
            'agree': int(np.sum(z_sig == emp_sig)),
            'disagree': int(np.sum(z_sig != emp_sig)),
            'only_z': int(np.sum(z_sig & ~emp_sig)),
            'only_empirical': int(np.sum(~z_sig & emp_sig)),
        }

        res = {
            'delta_obs': delta_obs, 'variant_occ': var_occ,
            'wt_occ': wt_occ[label],
            'empirical_p': empirical_p, 'q_values': q_values,
            'z_scores': z_scores, 'null_mean': null_mean, 'null_std': null_std,
            'variant_n_raw': len(var_f), 'variant_n_nc_matched': var_n,
            'all_clusters': prom_clusters,
            'significant_clusters': sig_clusters,
            'analysis_region': (a_start, a_end),
            'comparison': comparison,
        }
        results[label] = res

        n_sig_pos = int(np.sum(q_values[prom_slice] < 0.10))
        logging.info(f"  {label}: {n_sig_pos} positions FDR<0.10, "
                     f"{len(sig_clusters)} sig clusters")
        for c in sig_clusters:
            logging.info(f"    [{c['abs_start']}-{c['abs_end']}] "
                         f"w={c['width']}bp "
                         f"sum|delta|={c['sum_abs_delta']:.3f} "
                         f"p={c['sum_p']:.4f} dir={c['direction']}")

    return results


# ============================================================================
# Phase 5: Filter Optimization
# ============================================================================

def filter_optimization(rd, wt_idx, var_idx, bin_labels,
                        min_nuc_grid, max_nuc_percentiles,
                        promoter_start, promoter_end,
                        variant_position=None,
                        n_null_iterations=100,
                        random_seed=42, analysis_region=None,
                        cluster_threshold_quantile=0.95,
                        gap_tolerance=2, merge_distance=5,
                        n_workers=1):
    """Test detection across a grid of NC filters."""
    logging.info("=" * 60)
    logging.info("PHASE 5: Filter Optimization")
    logging.info("=" * 60)

    all_nc = rd.nuc_counts[rd.nuc_counts >= 0]
    max_nuc_values = {}
    for pctile in max_nuc_percentiles:
        if pctile >= 100:
            max_nuc_values[pctile] = None
        else:
            max_nuc_values[pctile] = int(np.percentile(all_nc, pctile))
    logging.info(f"  Max NC from percentiles: {max_nuc_values}")

    grid_results = {}

    for min_nc in min_nuc_grid:
        for max_pctile in max_nuc_percentiles:
            max_nc = max_nuc_values[max_pctile]
            label_key = f"min{min_nc}_maxP{max_pctile}"

            wt_f = rd.get_indices_filtered(wt_idx, min_nuc=min_nc,
                                           max_nuc=max_nc)
            var_f = rd.get_indices_filtered(var_idx, min_nuc=min_nc,
                                            max_nuc=max_nc)

            if len(wt_f) < 50 or len(var_f) < 20:
                logging.info(f"  {label_key}: skipped "
                             f"(WT={len(wt_f)}, var={len(var_f)})")
                continue

            gt_nc = compute_ground_truth_nc(rd, wt_idx, min_nuc=min_nc,
                                            max_nuc=max_nc)
            if gt_nc is None:
                continue

            null_res = run_null_calibration(
                rd, wt_idx, gt_nc, coverage_level=len(var_f),
                min_nuc=min_nc, max_nuc=max_nc,
                n_iterations=n_null_iterations,
                random_seed=random_seed,
                analysis_region=analysis_region,
                cluster_threshold_quantile=cluster_threshold_quantile,
                gap_tolerance=gap_tolerance, merge_distance=merge_distance,
                n_workers=max(1, n_workers // 4))

            var_res = variant_effect_test(
                rd, wt_idx, var_idx, gt_nc, null_res,
                promoter_start, promoter_end,
                min_nuc=min_nc, max_nuc=max_nc,
                random_seed=random_seed,
                cluster_threshold_quantile=cluster_threshold_quantile,
                gap_tolerance=gap_tolerance, merge_distance=merge_distance)

            metrics = {'wt_n': len(wt_f), 'var_n': len(var_f),
                       'min_nuc': min_nc, 'max_nuc_pctile': max_pctile,
                       'max_nuc_value': max_nc if max_nc is not None else -1}

            a_start_r = null_res['analysis_region'][0]

            for bl in bin_labels:
                if bl not in var_res:
                    continue
                vr = var_res[bl]
                prom_q = vr['q_values']
                metrics[f'{bl}_n_sig_fdr10'] = int(np.sum(prom_q < 0.10))
                metrics[f'{bl}_n_sig_clusters'] = len(
                    vr['significant_clusters'])
                metrics[f'{bl}_max_abs_delta'] = float(
                    np.max(np.abs(vr['delta_obs'])))

                null_med = np.median(
                    np.abs(null_res['null_delta'][
                        :, bin_labels.index(bl), :]).flatten())
                if null_med > 0:
                    metrics[f'{bl}_snr'] = float(
                        np.max(np.abs(vr['delta_obs'])) / null_med)
                else:
                    metrics[f'{bl}_snr'] = float('nan')

                if variant_position is not None:
                    vp_rel = variant_position - a_start_r
                    if 0 <= vp_rel < null_res['analysis_length']:
                        metrics[f'{bl}_delta_at_variant'] = float(
                            vr['delta_obs'][vp_rel])

            grid_results[label_key] = metrics
            logging.info(f"  {label_key}: WT={len(wt_f):,}, var={len(var_f):,}")

    return grid_results


# ============================================================================
# Phase 6: Power Analysis
# ============================================================================

def power_analysis(rd, wt_idx, var_idx, ground_truth_nc,
                   null_results_by_depth, coverage_grid,
                   promoter_start, promoter_end,
                   min_nuc=None, max_nuc=None,
                   n_resamples=50, random_seed=42,
                   variant_position=None,
                   cluster_threshold_quantile=0.95,
                   gap_tolerance=2, merge_distance=5):
    """Detection rate vs coverage depth."""
    logging.info("=" * 60)
    logging.info("PHASE 6: Power Analysis")
    logging.info("=" * 60)

    bin_labels = rd.bin_labels
    var_f = rd.get_indices_filtered(var_idx, min_nuc=min_nuc, max_nuc=max_nuc)
    n_var = len(var_f)

    coverage_grid = sorted([d for d in coverage_grid if d <= n_var],
                           reverse=True)
    logging.info(f"  Variant reads: {n_var}, depths: {coverage_grid}")

    rng = np.random.default_rng(random_seed)

    first_null = list(null_results_by_depth.values())[0]
    a_start, a_end = first_null['analysis_region']
    analysis_length = a_end - a_start
    col_indices = np.arange(a_start, a_end)
    prom_rel_start = max(0, promoter_start - a_start)
    prom_rel_end = min(analysis_length, promoter_end - a_start)

    nc_vals = ground_truth_nc['nc_vals']
    nc_fracs = ground_truth_nc['nc_fracs']

    results = {}

    for depth in coverage_grid:
        available_depths = sorted(null_results_by_depth.keys())
        closest = min(available_depths, key=lambda d: abs(d - depth))
        null_res = null_results_by_depth[closest]

        detections = {l: {'any_sig_cluster': 0,
                          'any_sig_position_fdr10': 0,
                          'variant_pos_sig': 0,
                          'max_abs_delta': [],
                          'n_sig_positions': []}
                      for l in bin_labels}

        for rep in range(n_resamples):
            sub_idx = rng.choice(var_f, size=depth, replace=False)
            sub_matched, sub_n = nc_matched_subsample(
                sub_idx, rd.nuc_counts, nc_fracs, nc_vals,
                rng, replace=False)

            for bi, label in enumerate(bin_labels):
                sub_occ = rd.coverage_matrices[label][
                    np.ix_(sub_matched, col_indices)].mean(axis=0)
                delta_obs = sub_occ - null_res['wt_occ'][label]

                null_delta = null_res['null_delta'][:, bi, :]
                abs_null = np.abs(null_delta)
                abs_obs = np.abs(delta_obs)
                exceed = np.sum(abs_null >= abs_obs[np.newaxis, :], axis=0)
                emp_p = (exceed + 1) / (null_delta.shape[0] + 1)

                prom_p = emp_p[prom_rel_start:prom_rel_end]
                prom_q = benjamini_hochberg(prom_p)

                n_sig = int(np.sum(prom_q < 0.10))
                detections[label]['n_sig_positions'].append(n_sig)
                detections[label]['max_abs_delta'].append(
                    float(np.max(abs_obs)))
                if n_sig > 0:
                    detections[label]['any_sig_position_fdr10'] += 1

                # Cluster detection
                pos_thresh = np.percentile(
                    abs_null, cluster_threshold_quantile * 100, axis=0)
                sig_mask = abs_obs > pos_thresh
                clusters = _detect_clusters_from_mask(
                    sig_mask, abs_obs, delta_obs, gap_tolerance, merge_distance)

                null_csums = null_res['null_cluster_sums'].get(
                    label, np.array([]))
                has_sig = False
                for c in clusters:
                    if (c['end'] >= prom_rel_start
                            and c['start'] < prom_rel_end
                            and len(null_csums) > 0):
                        cp = float(np.mean(null_csums >= c['sum_abs_delta']))
                        if cp < 0.05:
                            has_sig = True
                            break
                if has_sig:
                    detections[label]['any_sig_cluster'] += 1

                if variant_position is not None:
                    vp_rel = variant_position - a_start
                    if 0 <= vp_rel < analysis_length:
                        q_full = np.ones(analysis_length)
                        q_full[prom_rel_start:prom_rel_end] = prom_q
                        if q_full[vp_rel] < 0.10:
                            detections[label]['variant_pos_sig'] += 1

        depth_results = {}
        for label in bin_labels:
            d = detections[label]
            depth_results[label] = {
                'detection_rate_cluster': d['any_sig_cluster'] / n_resamples,
                'detection_rate_position_fdr10':
                    d['any_sig_position_fdr10'] / n_resamples,
                'detection_rate_variant_pos':
                    d['variant_pos_sig'] / n_resamples,
                'mean_n_sig_positions': float(np.mean(d['n_sig_positions'])),
                'mean_max_abs_delta': float(np.mean(d['max_abs_delta'])),
            }
        results[depth] = depth_results

        logging.info(f"  N={depth}: " + ", ".join(
            f"{l[:3]}={depth_results[l]['detection_rate_cluster']:.0%}"
            for l in bin_labels))

    return results


# ============================================================================
# HDF5 Output
# ============================================================================

def write_results_hdf5(output_path, parse_stats, ground_truth_nc,
                       chromatin_test, null_results_primary,
                       null_results_by_depth, variant_results,
                       filter_results, power_results,
                       bin_labels, ref_length, ref_name,
                       promoter_start, promoter_end, args):
    logging.info(f"Writing results to {output_path}...")
    with h5py.File(output_path, 'w') as f:
        meta = f.create_group('metadata')
        meta.attrs['version'] = VERSION
        meta.attrs['date'] = datetime.now().isoformat()
        meta.attrs['reference_name'] = ref_name
        meta.attrs['reference_length'] = ref_length
        meta.attrs['promoter_start'] = promoter_start
        meta.attrs['promoter_end'] = promoter_end
        meta.attrs['bin_labels'] = [l.encode() for l in bin_labels]
        if args.variant_id:
            meta.attrs['variant_id'] = args.variant_id
        if args.variant_position is not None:
            meta.attrs['variant_position'] = args.variant_position
        for k, v in parse_stats.items():
            meta.attrs[f'parse_{k}'] = v
        if null_results_primary:
            ar = null_results_primary['analysis_region']
            meta.attrs['analysis_start'] = ar[0]
            meta.attrs['analysis_end'] = ar[1]

        if ground_truth_nc is not None:
            gtn = f.create_group('ground_truth_nc')
            gtn.create_dataset('nc_vals', data=ground_truth_nc['nc_vals'])
            gtn.create_dataset('nc_fracs', data=ground_truth_nc['nc_fracs'])
            gtn.attrs['n_reads'] = ground_truth_nc['n_reads']

        if chromatin_test is not None:
            csg = f.create_group('chromatin_shift')
            for k, v in chromatin_test.items():
                if v is not None and isinstance(v, (int, float, str, bool)):
                    csg.attrs[k] = v
                elif isinstance(v, dict):
                    sg = csg.create_group(k)
                    for kk, vv in v.items():
                        sg.attrs[str(kk)] = vv

        if null_results_primary is not None:
            ng = f.create_group('null_calibration')
            ng.attrs['coverage_level'] = null_results_primary['coverage_level']
            ng.attrs['n_iterations'] = null_results_primary['n_iterations']
            ng.create_dataset('null_delta',
                              data=null_results_primary['null_delta'],
                              compression='gzip', compression_opts=4)
            for label in bin_labels:
                lg = ng.create_group(safe_hdf5_name(label))
                summ = null_results_primary['summary'][label]
                lg.create_dataset('pos_null_mean', data=summ['pos_null_mean'],
                                  compression='gzip')
                lg.create_dataset('pos_null_std', data=summ['pos_null_std'],
                                  compression='gzip')
                lg.create_dataset('wt_occ',
                                  data=null_results_primary['wt_occ'][label],
                                  compression='gzip')
                for k, v in summ['global_abs_delta_percentiles'].items():
                    lg.attrs[f'null_abs_delta_p{k}'] = v
                csums = null_results_primary['null_cluster_sums'].get(
                    label, np.array([]))
                if len(csums) > 0:
                    lg.create_dataset('null_cluster_sums', data=csums)
                cwidths = null_results_primary['null_cluster_widths'].get(
                    label, np.array([]))
                if len(cwidths) > 0:
                    lg.create_dataset('null_cluster_widths', data=cwidths)

        # Null summaries at other depths (no full delta matrix)
        if null_results_by_depth:
            ndg = f.create_group('null_by_depth')
            primary_depth = (null_results_primary['coverage_level']
                             if null_results_primary else -1)
            for depth, null_res in null_results_by_depth.items():
                if depth == primary_depth:
                    continue
                dg = ndg.create_group(str(depth))
                dg.attrs['coverage_level'] = depth
                dg.attrs['n_iterations'] = null_res['n_iterations']
                for label in bin_labels:
                    lg = dg.create_group(safe_hdf5_name(label))
                    summ = null_res['summary'][label]
                    lg.create_dataset('pos_null_mean',
                                      data=summ['pos_null_mean'],
                                      compression='gzip')
                    lg.create_dataset('pos_null_std',
                                      data=summ['pos_null_std'],
                                      compression='gzip')

        if variant_results is not None:
            vg = f.create_group('variant_results')
            for label in bin_labels:
                if label not in variant_results:
                    continue
                vr = variant_results[label]
                lg = vg.create_group(safe_hdf5_name(label))
                for key in ['delta_obs', 'variant_occ', 'wt_occ',
                            'empirical_p', 'q_values', 'z_scores']:
                    lg.create_dataset(key, data=vr[key], compression='gzip')
                lg.attrs['variant_n_raw'] = vr['variant_n_raw']
                lg.attrs['variant_n_nc_matched'] = vr['variant_n_nc_matched']
                for k, v in vr.get('comparison', {}).items():
                    lg.attrs[f'comparison_{k}'] = v

                if vr['significant_clusters']:
                    cgrp = lg.create_group('significant_clusters')
                    for i, cl in enumerate(vr['significant_clusters']):
                        sg = cgrp.create_group(f'c{i}')
                        for k, v in cl.items():
                            if isinstance(v, (int, float, str, bool)):
                                sg.attrs[k] = v

        if filter_results:
            fg = f.create_group('filter_optimization')
            for key, metrics in filter_results.items():
                sg = fg.create_group(key)
                for k, v in metrics.items():
                    if v is not None and isinstance(v, (int, float, str, bool)):
                        sg.attrs[k] = v

        if power_results:
            pg = f.create_group('power_analysis')
            for depth, depth_res in power_results.items():
                dg = pg.create_group(str(depth))
                for label, data in depth_res.items():
                    lg = dg.create_group(safe_hdf5_name(label))
                    for k, v in data.items():
                        if isinstance(v, (int, float)):
                            lg.attrs[k] = v

    logging.info(f"Results written to {output_path}")


# ============================================================================
# PDF Diagnostic Report
# ============================================================================

def generate_diagnostic_pdf(pdf_path, chromatin_test, null_results_primary,
                            variant_results, filter_results, power_results,
                            bin_labels, ref_length, promoter_start,
                            promoter_end, variant_position=None,
                            analysis_region=None):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages

    BIN_COLORS = {
        'sub-TF_10-19bp': '#66c2a5', 'TF_20-40bp': '#fc8d62',
        'PIC_41-80bp': '#8da0cb', 'Nucleosome_81plusbp': '#e78ac3',
    }
    BIN_SHORT = {
        'sub-TF_10-19bp': 'sub-TF', 'TF_20-40bp': 'TF',
        'PIC_41-80bp': 'PIC', 'Nucleosome_81plusbp': 'NUC',
    }

    a_start = analysis_region[0] if analysis_region else 0
    a_end = analysis_region[1] if analysis_region else ref_length
    x = np.arange(a_start, a_end)
    vp_rel = (variant_position - a_start
              if variant_position is not None else None)

    logging.info(f"Generating diagnostic PDF: {pdf_path}")

    with PdfPages(pdf_path) as pdf:
        # ---- Title page (ensures PDF is never empty) ----
        fig, ax = plt.subplots(figsize=(14, 3))
        ax.axis('off')
        ax.text(0.5, 0.7, f'MPRA Empirical Analysis v{VERSION}',
                fontsize=18, ha='center', va='center', fontweight='bold')
        info_lines = []
        if chromatin_test is not None:
            info_lines.append(f"WT reads: {chromatin_test.get('wt_n', '?'):,}")
            info_lines.append(f"Variant reads: {chromatin_test.get('var_n', '?'):,}")
        if variant_results is not None:
            info_lines.append("Variant results: YES")
        else:
            info_lines.append("Variant results: NONE (check logs for filtering issues)")
        ax.text(0.5, 0.3, '\n'.join(info_lines),
                fontsize=11, ha='center', va='center', color='gray')
        pdf.savefig(fig, bbox_inches='tight')
        plt.close(fig)
        # ---- Page 1: NC distributions ----
        if chromatin_test and 'wt_nc_distribution' in chromatin_test:
            fig, axes = plt.subplots(1, 2, figsize=(14, 5))
            wt_dist = chromatin_test['wt_nc_distribution']
            var_dist = chromatin_test['var_nc_distribution']
            all_ncs = sorted(set(list(wt_dist.keys()) + list(var_dist.keys())))

            ax = axes[0]
            if all_ncs:
                wt_c = [wt_dist.get(nc, 0) for nc in all_ncs]
                var_c = [var_dist.get(nc, 0) for nc in all_ncs]
                wt_tot = max(sum(wt_c), 1)
                var_tot = max(sum(var_c), 1)
                w = 0.35
                pos = np.arange(len(all_ncs))
                ax.bar(pos - w/2, [c/wt_tot for c in wt_c], w,
                       label='WT', color='#4a86c8', alpha=0.7)
                ax.bar(pos + w/2, [c/var_tot for c in var_c], w,
                       label='Variant', color='#e85d50', alpha=0.7)
                ax.set_xticks(pos)
                ax.set_xticklabels(all_ncs)
                ax.set_xlabel('Nucleosome Count')
                ax.set_ylabel('Fraction')
                ax.legend()
                ks_p = chromatin_test.get('ks_pval', float('nan'))
                ax.set_title(f'NC Distribution (KS p={ks_p:.2e})')

            ax = axes[1]
            if all_ncs:
                wt_cdf = np.cumsum([c/wt_tot for c in wt_c])
                var_cdf = np.cumsum([c/var_tot for c in var_c])
                ax.step(all_ncs, wt_cdf, where='mid',
                        label='WT', color='#4a86c8', linewidth=2)
                ax.step(all_ncs, var_cdf, where='mid',
                        label='Variant', color='#e85d50', linewidth=2)
                ax.set_xlabel('Nucleosome Count')
                ax.set_ylabel('Cumulative Fraction')
                ax.legend()
                ax.set_title('NC CDF')

            fig.suptitle('Phase 2: Chromatin Shift Test', fontsize=14)
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

        # ---- Page 2: Null calibration QQ + null variability ----
        if null_results_primary is not None:
            fig, axes = plt.subplots(len(bin_labels), 2,
                                     figsize=(14, 3.5 * len(bin_labels)))
            if len(bin_labels) == 1:
                axes = axes.reshape(1, -1)

            for i, label in enumerate(bin_labels):
                summ = null_results_primary['summary'][label]

                ax = axes[i, 0]
                null_flat = null_results_primary['null_delta'][
                    :, i, :].flatten()
                n_qq = min(10000, len(null_flat))
                rng_qq = np.random.default_rng(42)
                qq_sample = np.sort(rng_qq.choice(null_flat, size=n_qq,
                                                   replace=False))
                theoretical = np.sort(rng_qq.normal(0, np.std(null_flat),
                                                     size=n_qq))
                ax.scatter(theoretical, qq_sample, s=1, alpha=0.3,
                           color=BIN_COLORS.get(label, 'gray'))
                lim = max(abs(qq_sample).max(), abs(theoretical).max()) * 1.1
                ax.plot([-lim, lim], [-lim, lim], 'k--', linewidth=0.5)
                ax.set_xlabel('Theoretical (Normal)')
                ax.set_ylabel('Observed Null Δ')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: QQ Plot')

                ax = axes[i, 1]
                ax.fill_between(x, summ['pos_null_std'], alpha=0.4,
                                color=BIN_COLORS.get(label, 'gray'))
                ax.plot(x, summ['pos_null_std'], linewidth=0.8,
                        color=BIN_COLORS.get(label, 'gray'))
                ax.set_ylabel('Null Δ std')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: '
                             f'Per-Position Null Variability')
                if vp_rel is not None and vp_rel < len(x):
                    ax.axvline(x[vp_rel], color='red', alpha=0.5,
                               linestyle='--', linewidth=1)

            fig.suptitle('Phase 3: Null Calibration Diagnostics', fontsize=14)
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

        # ---- Page 3: Occupancy and delta ----
        if variant_results is not None:
            fig, axes = plt.subplots(len(bin_labels), 2,
                                     figsize=(14, 3.5 * len(bin_labels)))
            if len(bin_labels) == 1:
                axes = axes.reshape(1, -1)

            for i, label in enumerate(bin_labels):
                if label not in variant_results:
                    continue
                vr = variant_results[label]
                color = BIN_COLORS.get(label, 'gray')

                ax = axes[i, 0]
                ax.plot(x, vr['wt_occ'], linewidth=1.5,
                        color='#4a86c8', alpha=0.8, label='WT')
                ax.plot(x, vr['variant_occ'], linewidth=1.5,
                        color='#e85d50', alpha=0.8, label='Variant')
                ax.set_ylabel('Occupancy')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: Occupancy')
                ax.legend(fontsize=8, frameon=False)
                if vp_rel is not None and vp_rel < len(x):
                    ax.axvline(x[vp_rel], color='red', alpha=0.3,
                               linestyle='--')

                ax = axes[i, 1]
                delta = vr['delta_obs']
                ax.fill_between(x, delta, alpha=0.3, color=color)
                ax.plot(x, delta, linewidth=0.8, color=color)
                ax.axhline(0, color='gray', linewidth=0.5)
                for cl in vr.get('significant_clusters', []):
                    cs, ce = cl['start'], cl['end']
                    if cs < len(x) and ce < len(x):
                        ax.axvspan(x[cs], x[ce], alpha=0.2, color='red')
                ax.set_ylabel('Δ (variant - WT)')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: '
                             f'Occupancy Difference')
                if vp_rel is not None and vp_rel < len(x):
                    ax.axvline(x[vp_rel], color='red', alpha=0.3,
                               linestyle='--')

            fig.suptitle('Phase 4: Variant Effect Testing', fontsize=14)
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

        # ---- Page 4: Empirical p + Z-score comparison ----
        if variant_results is not None:
            fig, axes = plt.subplots(len(bin_labels), 2,
                                     figsize=(14, 3.5 * len(bin_labels)))
            if len(bin_labels) == 1:
                axes = axes.reshape(1, -1)

            for i, label in enumerate(bin_labels):
                if label not in variant_results:
                    continue
                vr = variant_results[label]

                ax = axes[i, 0]
                neg_log_p = -np.log10(np.maximum(vr['empirical_p'], 1e-10))
                ax.plot(x, neg_log_p, linewidth=0.8,
                        color=BIN_COLORS.get(label, 'gray'))
                ax.axhline(-np.log10(0.05), color='orange', linestyle='--',
                            linewidth=0.5, label='p=0.05')
                ax.axhline(-np.log10(0.01), color='red', linestyle='--',
                            linewidth=0.5, label='p=0.01')
                ax.set_ylabel('-log10(p)')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: Empirical P')
                ax.legend(fontsize=7, frameon=False)
                if vp_rel is not None and vp_rel < len(x):
                    ax.axvline(x[vp_rel], color='red', alpha=0.3,
                               linestyle='--')

                ax = axes[i, 1]
                z = vr['z_scores']
                ax.plot(x, z, linewidth=0.8,
                        color=BIN_COLORS.get(label, 'gray'))
                ax.axhline(0, color='gray', linewidth=0.5)
                ax.axhline(2, color='orange', linestyle=':', linewidth=0.5)
                ax.axhline(-2, color='orange', linestyle=':', linewidth=0.5)
                ax.set_ylabel('Z-score')
                comp = vr.get('comparison', {})
                ax.set_title(f'{BIN_SHORT.get(label, label)}: Z '
                             f'(agree={comp.get("agree","?")}, '
                             f'z_only={comp.get("only_z","?")}, '
                             f'emp_only={comp.get("only_empirical","?")})')
                if vp_rel is not None and vp_rel < len(x):
                    ax.axvline(x[vp_rel], color='red', alpha=0.3,
                               linestyle='--')

            fig.suptitle('Significance: Empirical vs Z-Score', fontsize=14)
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

        # ---- Page 5: Filter optimization heatmaps ----
        if filter_results:
            min_nucs = sorted(set(v['min_nuc']
                                  for v in filter_results.values()))
            max_pctiles = sorted(set(v['max_nuc_pctile']
                                     for v in filter_results.values()))

            for label in bin_labels:
                fig, axes = plt.subplots(1, 2, figsize=(14, 5))
                # SNR heatmap
                ax = axes[0]
                grid = np.full((len(min_nucs), len(max_pctiles)), np.nan)
                for key, m in filter_results.items():
                    mi = min_nucs.index(m['min_nuc'])
                    pi = max_pctiles.index(m['max_nuc_pctile'])
                    grid[mi, pi] = m.get(f'{label}_snr', np.nan)
                im = ax.imshow(grid, aspect='auto', origin='lower',
                               cmap='YlOrRd')
                ax.set_xticks(range(len(max_pctiles)))
                ax.set_xticklabels([f'{p}%' for p in max_pctiles])
                ax.set_yticks(range(len(min_nucs)))
                ax.set_yticklabels(min_nucs)
                ax.set_xlabel('Max NC Percentile')
                ax.set_ylabel('Min NC')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: SNR')
                plt.colorbar(im, ax=ax)

                # N sig clusters heatmap
                ax = axes[1]
                grid2 = np.full((len(min_nucs), len(max_pctiles)), np.nan)
                for key, m in filter_results.items():
                    mi = min_nucs.index(m['min_nuc'])
                    pi = max_pctiles.index(m['max_nuc_pctile'])
                    grid2[mi, pi] = m.get(f'{label}_n_sig_clusters', np.nan)
                im2 = ax.imshow(grid2, aspect='auto', origin='lower',
                                cmap='YlOrRd')
                ax.set_xticks(range(len(max_pctiles)))
                ax.set_xticklabels([f'{p}%' for p in max_pctiles])
                ax.set_yticks(range(len(min_nucs)))
                ax.set_yticklabels(min_nucs)
                ax.set_xlabel('Max NC Percentile')
                ax.set_ylabel('Min NC')
                ax.set_title(f'{BIN_SHORT.get(label, label)}: Sig Clusters')
                plt.colorbar(im2, ax=ax)

                fig.suptitle(f'Phase 5: Filter Optimization — '
                             f'{BIN_SHORT.get(label, label)}', fontsize=14)
                plt.tight_layout()
                pdf.savefig(fig, bbox_inches='tight')
                plt.close(fig)

        # ---- Page 6: Power curves ----
        if power_results:
            fig, axes = plt.subplots(2, 2, figsize=(12, 10))
            axes_flat = axes.flatten()

            for i, label in enumerate(bin_labels):
                if i >= len(axes_flat):
                    break
                ax = axes_flat[i]
                depths = sorted(power_results.keys(), reverse=True)
                det_c = [power_results[d][label]['detection_rate_cluster']
                         for d in depths]
                det_p = [power_results[d][label]['detection_rate_position_fdr10']
                         for d in depths]
                ax.plot(depths, det_c, 'o-', color='#e85d50', linewidth=2,
                        markersize=5, label='Sig cluster')
                ax.plot(depths, det_p, 's--', color='#4a86c8', linewidth=2,
                        markersize=5, label='Sig position (FDR<0.10)')

                if variant_position is not None:
                    det_v = [power_results[d][label]['detection_rate_variant_pos']
                             for d in depths]
                    ax.plot(depths, det_v, '^:', color='#2ca02c', linewidth=2,
                            markersize=5, label='Variant pos sig')

                ax.axhline(0.80, color='gray', linestyle='--', linewidth=0.5)
                ax.set_xlabel('Coverage (reads)')
                ax.set_ylabel('Detection Rate')
                ax.set_title(BIN_SHORT.get(label, label))
                ax.legend(fontsize=8, frameon=False)
                ax.set_ylim(-0.05, 1.05)

            fig.suptitle('Phase 6: Power Analysis', fontsize=14)
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

        # ---- Page 7: Summary table ----
        if variant_results:
            fig, ax = plt.subplots(figsize=(14, 6))
            ax.axis('off')
            col_labels = ['Bin', 'N reads', 'Max |Δ|', 'Sig pos (FDR<0.10)',
                          'Sig clusters', 'Top cluster Σ|Δ|',
                          'Top cluster p', 'Direction']
            table_data = []
            for label in bin_labels:
                if label not in variant_results:
                    continue
                vr = variant_results[label]
                sig_c = vr.get('significant_clusters', [])
                top_c = (max(sig_c, key=lambda c: c['sum_abs_delta'])
                         if sig_c else None)
                n_sig = int(np.sum(vr['q_values'] < 0.10))
                table_data.append([
                    BIN_SHORT.get(label, label),
                    str(vr['variant_n_nc_matched']),
                    f"{np.max(np.abs(vr['delta_obs'])):.4f}",
                    str(n_sig), str(len(sig_c)),
                    f"{top_c['sum_abs_delta']:.3f}" if top_c else "—",
                    f"{top_c['sum_p']:.4f}" if top_c else "—",
                    top_c['direction'] if top_c else "—",
                ])

            if table_data:
                table = ax.table(cellText=table_data, colLabels=col_labels,
                                 loc='center', cellLoc='center')
                table.auto_set_font_size(False)
                table.set_fontsize(10)
                table.scale(1, 1.5)
            ax.set_title('Analysis Summary', fontsize=14, pad=20)
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

    logging.info(f"PDF written to {pdf_path}")


# ============================================================================
# Notebook Template
# ============================================================================

def generate_notebook_template(notebook_path, hdf5_path, bin_labels):
    import json as json_mod

    cells = []
    def md(s):
        cells.append({"cell_type": "markdown", "metadata": {}, "source": [s]})
    def code(s):
        cells.append({"cell_type": "code", "execution_count": None,
                       "metadata": {}, "outputs": [], "source": [s]})

    md("# MPRA Empirical Analysis — Interactive Explorer\n\n"
       f"HDF5: `{hdf5_path}`")

    code("import h5py\nimport numpy as np\n"
         "import matplotlib.pyplot as plt\n"
         "from ipywidgets import interact, Dropdown\n"
         "%matplotlib inline\n\n"
         f"h5_path = '{hdf5_path}'\n"
         "f = h5py.File(h5_path, 'r')\n"
         "bin_labels = [b.decode() for b in f['metadata'].attrs['bin_labels']]\n"
         "prom_s = f['metadata'].attrs['promoter_start']\n"
         "prom_e = f['metadata'].attrs['promoter_end']\n"
         "vpos = f['metadata'].attrs.get('variant_position', None)\n"
         "a_start = f['metadata'].attrs.get('analysis_start', 0)\n"
         "a_end = f['metadata'].attrs.get('analysis_end', "
         "f['metadata'].attrs['reference_length'])\n"
         "print(f'Bins: {bin_labels}')\n"
         "print(f'Promoter: {prom_s}-{prom_e}')\n"
         "print(f'Variant position: {vpos}')\n"
         "print(f'\\nHDF5 groups: {list(f.keys())}')\n"
         "has_variant = 'variant_results' in f\n"
         "has_null = 'null_calibration' in f\n"
         "has_power = 'power_analysis' in f\n"
         "print(f'Variant results: {has_variant}')\n"
         "print(f'Null calibration: {has_null}')\n"
         "print(f'Power analysis: {has_power}')\n"
         "if not has_variant:\n"
         "    print('\\n*** WARNING: No variant results found. ***')\n"
         "    print('Check script logs for variant detection / filtering issues.')")

    md("## Occupancy & Δ Explorer")

    code(
        "def sn(n):\n"
        "    return n.replace(' ','_').replace('(','').replace(')','')."
        "replace('+','plus').replace('>','to').replace(':','_')\n\n"
        "if not has_variant:\n"
        "    print('No variant results available. Skipping occupancy explorer.')\n"
        "else:\n"
        "    @interact(bin_label=Dropdown(options=bin_labels, description='Bin:'))\n"
        "    def plot_occ(bin_label):\n"
        "        sl = sn(bin_label)\n"
        "        vr = f['variant_results'].get(sl)\n"
        "        if vr is None:\n"
        "            print(f'No results for {bin_label}'); return\n"
        "        wt = vr['wt_occ'][:]; vo = vr['variant_occ'][:]\n"
        "        delta = vr['delta_obs'][:]; ep = vr['empirical_p'][:]\n"
        "        z = vr['z_scores'][:]\n"
        "        x = np.arange(a_start, a_start + len(wt))\n\n"
        "        fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)\n"
        "        axes[0].plot(x, wt, label='WT', color='#4a86c8')\n"
        "        axes[0].plot(x, vo, label='Variant', color='#e85d50')\n"
        "        axes[0].set_ylabel('Occupancy'); axes[0].legend(frameon=False)\n"
        "        axes[0].set_title(f'{bin_label}: Occupancy')\n\n"
        "        axes[1].fill_between(x, delta, alpha=0.3)\n"
        "        axes[1].plot(x, delta, lw=0.8)\n"
        "        axes[1].axhline(0, color='gray', lw=0.5)\n"
        "        axes[1].set_ylabel('Δ'); axes[1].set_title('Δ (variant - WT)')\n\n"
        "        axes[2].plot(x, -np.log10(np.maximum(ep, 1e-10)), "
        "color='#66c2a5', label='Empirical -log10(p)')\n"
        "        axes[2].plot(x, np.abs(z), color='#fc8d62', alpha=0.5, "
        "label='|Z|')\n"
        "        axes[2].axhline(-np.log10(0.05), color='gray', ls='--')\n"
        "        axes[2].set_ylabel('-log10(p) / |Z|')\n"
        "        axes[2].legend(frameon=False)\n\n"
        "        if vpos is not None:\n"
        "            for ax in axes: ax.axvline(vpos, color='red', alpha=0.3, ls='--')\n"
        "        plt.tight_layout(); plt.show()")

    md("## Cluster Browser")

    code(
        "if not has_variant:\n"
        "    print('No variant results available.')\n"
        "else:\n"
        "    for bl in bin_labels:\n"
        "        sl = sn(bl)\n"
        "        vr = f['variant_results'].get(sl)\n"
        "        if vr is None: continue\n"
        "        sc = vr.get('significant_clusters')\n"
        "        if sc is None:\n"
        "            print(f'{bl}: no significant clusters'); continue\n"
        "        print(f'\\n{bl}:')\n"
        "        for cn in sorted(sc.keys()):\n"
        "            c = sc[cn]\n"
        "            print(f\"  {c.attrs['abs_start']}-{c.attrs['abs_end']} \"\n"
        "                  f\"(w={c.attrs['width']}bp) \"\n"
        "                  f\"sum|Δ|={c.attrs['sum_abs_delta']:.3f} \"\n"
        "                  f\"p={c.attrs['sum_p']:.4f} \"\n"
        "                  f\"dir={c.attrs['direction']}\")")

    md("## Null Distribution")

    code(
        "if not has_null:\n"
        "    print('No null calibration data available.')\n"
        "else:\n"
        "    @interact(bin_label=Dropdown(options=bin_labels, description='Bin:'))\n"
        "    def plot_null(bin_label):\n"
        "        bi = bin_labels.index(bin_label)\n"
        "        nd = f['null_calibration']['null_delta'][:, bi, :].flatten()\n"
        "        fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
        "        axes[0].hist(nd, bins=100, density=True, alpha=0.7)\n"
        "        axes[0].set_xlabel('Null Δ')\n"
        "        axes[0].set_title(f'{bin_label}: Null Δ')\n"
        "        ab = np.abs(nd)\n"
        "        axes[1].hist(ab, bins=100, density=True, alpha=0.7, color='orange')\n"
        "        for p in [95, 99]:\n"
        "            v = np.percentile(ab, p)\n"
        "            axes[1].axvline(v, color='red', ls='--', label=f'p{p}={v:.4f}')\n"
        "        axes[1].set_xlabel('|Null Δ|'); axes[1].legend(fontsize=8)\n"
        "        plt.tight_layout(); plt.show()")

    md("## Power Curves")

    code(
        "if 'power_analysis' in f:\n"
        "    pg = f['power_analysis']\n"
        "    depths = sorted([int(d) for d in pg.keys()], reverse=True)\n"
        "    fig, axes = plt.subplots(2, 2, figsize=(12, 8))\n"
        "    for i, bl in enumerate(bin_labels):\n"
        "        sl = sn(bl); ax = axes.flat[i]\n"
        "        rc = [float(pg[str(d)][sl].attrs['detection_rate_cluster']) "
        "for d in depths]\n"
        "        rp = [float(pg[str(d)][sl].attrs['detection_rate_position_fdr10']) "
        "for d in depths]\n"
        "        ax.plot(depths, rc, 'o-', label='Cluster')\n"
        "        ax.plot(depths, rp, 's--', label='Position')\n"
        "        ax.axhline(0.80, color='gray', ls='--', alpha=0.5)\n"
        "        ax.set_xlabel('Coverage'); ax.set_ylabel('Detection Rate')\n"
        "        ax.set_title(bl); ax.legend(fontsize=8)\n"
        "    plt.tight_layout(); plt.show()\n"
        "else:\n    print('No power analysis')")

    md("---\n*Close HDF5 when done:*")
    code("f.close()")

    nb = {"nbformat": 4, "nbformat_minor": 5,
          "metadata": {"kernelspec": {"display_name": "Python 3",
                       "language": "python", "name": "python3"},
                       "language_info": {"name": "python", "version": "3.10.0"}},
          "cells": cells}
    with open(notebook_path, 'w') as fout:
        json_mod.dump(nb, fout, indent=1)
    logging.info(f"Notebook written to {notebook_path}")


# ============================================================================
# Summary
# ============================================================================

def print_summary(chromatin_test, variant_results, power_results, bin_labels):
    logging.info("")
    logging.info("=" * 70)
    logging.info(f"ANALYSIS SUMMARY (v{VERSION})")
    logging.info("=" * 70)

    if chromatin_test is not None:
        logging.info("")
        logging.info("--- Chromatin Shift ---")
        sig = "***" if chromatin_test.get('ks_pval', 1) < 0.001 else ""
        logging.info(f"  KS={chromatin_test.get('ks_stat', 0):.4f}, "
                     f"p={chromatin_test.get('ks_pval', 1):.2e} {sig}, "
                     f"delta_mean_NC={chromatin_test.get('delta_mean_nc', 0):+.2f}")

    if variant_results is not None:
        logging.info("")
        logging.info("--- Variant Effect (Empirical delta) ---")
        for label in bin_labels:
            if label not in variant_results:
                continue
            vr = variant_results[label]
            n_sig = int(np.sum(vr['q_values'] < 0.10))
            n_clust = len(vr.get('significant_clusters', []))
            logging.info(f"  {label}: {n_sig} pos FDR<0.10, "
                         f"{n_clust} sig clusters, "
                         f"max |delta|={np.max(np.abs(vr['delta_obs'])):.4f}")
            for cl in vr.get('significant_clusters', []):
                logging.info(
                    f"    [{cl['abs_start']}-{cl['abs_end']}] "
                    f"w={cl['width']}bp sum|delta|={cl['sum_abs_delta']:.3f} "
                    f"p={cl['sum_p']:.4f} dir={cl['direction']}")

    if power_results:
        logging.info("")
        logging.info("--- Power Analysis ---")
        for depth in sorted(power_results.keys(), reverse=True):
            parts = [f"{l[:3]}={power_results[depth][l]['detection_rate_cluster']:.0%}"
                     for l in bin_labels]
            logging.info(f"  N={depth}: {', '.join(parts)}")


# ============================================================================
# Argument Parsing
# ============================================================================

def parse_args():
    p = argparse.ArgumentParser(
        description=f'Empirical MPRA Fiber-seq Analysis (v{VERSION})',
        formatter_class=argparse.RawDescriptionHelpFormatter)

    p.add_argument('--bam', required=True, help='Input BAM')
    p.add_argument('--output', required=True, help='Output HDF5')
    p.add_argument('--pdf', default=None, help='Diagnostic PDF')
    p.add_argument('--notebook', default=None, help='Notebook template')

    p.add_argument('--target-region', default=None, help='"chr" or "chr:start-end"')
    p.add_argument('--promoter-region', default=None, help='"start-end" (0-based)')

    p.add_argument('--variant-id', default=None)
    p.add_argument('--variant-position', type=int, default=None)
    p.add_argument('--variant-alt', default=None)

    p.add_argument('--n-null-iterations', type=int, default=500)
    p.add_argument('--n-power-resamples', type=int, default=50)
    p.add_argument('--n-filter-null-iters', type=int, default=100)
    p.add_argument('--random-seed', type=int, default=42)

    p.add_argument('--coverage-grid', default='50,100,200,500,750,1000,2000')
    p.add_argument('--min-nuc-grid', default='0,1,2,3,4,5')
    p.add_argument('--max-nuc-percentiles', default='85,90,95,100')

    p.add_argument('--min-nuc', type=int, default=None)
    p.add_argument('--max-nuc', type=int, default=None)

    p.add_argument('--cluster-threshold-quantile', type=float, default=0.95)
    p.add_argument('--absolute-delta-threshold', type=float, default=None)
    p.add_argument('--gap-tolerance', type=int, default=2)
    p.add_argument('--merge-distance', type=int, default=5)

    p.add_argument('--threads', type=int, default=None)
    p.add_argument('--verbose', action='store_true')

    p.add_argument('--skip-filter-optimization', action='store_true')
    p.add_argument('--skip-power-analysis', action='store_true')

    return p.parse_args()


# ============================================================================
# Main
# ============================================================================

def main():
    args = parse_args()
    setup_logging(args.verbose)

    if args.threads is None:
        args.threads = min(os.cpu_count() or 1, args.n_null_iterations)

    logging.info(f"mpra_empirical_analysis.py v{VERSION}")
    logging.info(f"BAM: {args.bam}")
    logging.info(f"Output: {args.output}")
    logging.info(f"Threads: {args.threads}")
    start_time = time.time()

    if args.pdf is None:
        args.pdf = args.output.rsplit('.', 1)[0] + '.pdf'
    if args.notebook is None:
        args.notebook = args.output.rsplit('.', 1)[0] + '_explorer.ipynb'

    size_bins = [FOOTPRINT_BINS['sub_TF'], FOOTPRINT_BINS['TF'],
                 FOOTPRINT_BINS['PIC'], FOOTPRINT_BINS['NUC']]
    bin_labels = [b[2] for b in size_bins]

    target_chrom, target_start, target_end = parse_target_region(
        args.target_region)

    coverage_grid = [int(d) for d in args.coverage_grid.split(',')]
    min_nuc_grid = [int(d) for d in args.min_nuc_grid.split(',')]
    max_nuc_pctiles = [int(d) for d in args.max_nuc_percentiles.split(',')]

    # ================================================================
    # Phase 1: Parse BAM
    # ================================================================
    logging.info("=" * 60)
    logging.info("PHASE 1: Parse & Setup")
    logging.info("=" * 60)

    rd, ref_length, ref_name, parse_stats = parse_bam(
        args.bam, size_bins, bin_labels, target_chrom=target_chrom)

    wt_idx = rd.wt_indices
    logging.info(f"WT: {len(wt_idx):,}")
    for vid, vidx in rd.variant_indices.items():
        logging.info(f"Variant '{vid}': {len(vidx):,}")

    # Promoter region
    if args.promoter_region:
        ps = args.promoter_region.split('-')
        prom_s, prom_e = int(ps[0]), int(ps[1])
    elif target_start is not None:
        prom_s, prom_e = target_start, target_end
    else:
        prom_s, prom_e = 0, ref_length
    logging.info(f"Promoter: {prom_s}-{prom_e} ({prom_e - prom_s} bp)")

    analysis_region = (prom_s, prom_e)

    # Target variant
    if args.variant_id and args.variant_id in rd.variant_indices:
        tgt_vid = args.variant_id
        tgt_vidx = rd.variant_indices[tgt_vid]
        logging.info(f"Using specified variant: {tgt_vid} "
                     f"({len(tgt_vidx):,} reads)")
    elif args.variant_id and args.variant_id not in rd.variant_indices:
        logging.error(f"Variant '{args.variant_id}' not found in BAM. "
                      f"Available: {list(rd.variant_indices.keys())}")
        tgt_vid, tgt_vidx = None, None
    elif len(rd.variant_indices) == 1:
        tgt_vid = list(rd.variant_indices.keys())[0]
        tgt_vidx = rd.variant_indices[tgt_vid]
        logging.info(f"Auto-detected variant: {tgt_vid} "
                     f"({len(tgt_vidx):,} reads)")
    elif len(rd.variant_indices) > 1:
        # Multiple variants: pick the one with the most reads
        tgt_vid = max(rd.variant_indices.keys(),
                      key=lambda v: len(rd.variant_indices[v]))
        tgt_vidx = rd.variant_indices[tgt_vid]
        logging.warning(f"Multiple variants found: "
                        f"{list(rd.variant_indices.keys())}")
        logging.warning(f"Auto-selected largest: {tgt_vid} "
                        f"({len(tgt_vidx):,} reads). "
                        f"Use --variant-id to override.")
    else:
        tgt_vid, tgt_vidx = None, None
        logging.error("No variant reads found in BAM!")

    vpos = args.variant_position

    # ================================================================
    # Ground Truth NC
    # ================================================================
    ground_truth_nc = compute_ground_truth_nc(
        rd, wt_idx, min_nuc=args.min_nuc, max_nuc=args.max_nuc)

    # ================================================================
    # Phase 2: Chromatin Shift
    # ================================================================
    chromatin_test = None
    if tgt_vidx is not None:
        chromatin_test = chromatin_shift_test(
            rd, wt_idx, tgt_vidx,
            min_nuc=args.min_nuc, max_nuc=args.max_nuc)
    else:
        logging.warning("Skipping Phase 2 (chromatin shift): "
                        "no variant identified.")

    # ================================================================
    # Phase 3: Null Calibration
    # ================================================================
    null_results_primary = None
    null_results_by_depth = {}

    if ground_truth_nc is not None and tgt_vidx is not None:
        var_f = rd.get_indices_filtered(tgt_vidx, min_nuc=args.min_nuc,
                                         max_nuc=args.max_nuc)
        primary_depth = len(var_f)
        logging.info(f"Variant reads after NC filter: {primary_depth:,} "
                     f"(from {len(tgt_vidx):,} raw)")

        if primary_depth < 20:
            logging.warning(f"Too few variant reads after filtering "
                            f"({primary_depth}). Skipping null calibration. "
                            f"Check --min-nuc / --max-nuc settings.")
        else:
            logging.info("=" * 60)
            logging.info("PHASE 3: Null Calibration")
            logging.info("=" * 60)
            logging.info(f"Primary null depth: {primary_depth}")

            t0 = time.time()
            null_results_primary = run_null_calibration(
                rd, wt_idx, ground_truth_nc, coverage_level=primary_depth,
                min_nuc=args.min_nuc, max_nuc=args.max_nuc,
                n_iterations=args.n_null_iterations,
                random_seed=args.random_seed,
                analysis_region=analysis_region,
                cluster_threshold_quantile=args.cluster_threshold_quantile,
                absolute_delta_threshold=args.absolute_delta_threshold,
                gap_tolerance=args.gap_tolerance,
                merge_distance=args.merge_distance,
                n_workers=args.threads)
            null_results_by_depth[primary_depth] = null_results_primary
            logging.info(f"  Primary null time: {time.time() - t0:.1f}s")

        # Coverage grid nulls (lightweight: fewer iterations)
        if not args.skip_power_analysis:
            grid_depths = [d for d in coverage_grid
                           if d != primary_depth and d <= len(var_f)]
            for depth in grid_depths:
                t1 = time.time()
                nr = run_null_calibration(
                    rd, wt_idx, ground_truth_nc, coverage_level=depth,
                    min_nuc=args.min_nuc, max_nuc=args.max_nuc,
                    n_iterations=min(200, args.n_null_iterations),
                    random_seed=args.random_seed + depth,
                    analysis_region=analysis_region,
                    cluster_threshold_quantile=args.cluster_threshold_quantile,
                    absolute_delta_threshold=args.absolute_delta_threshold,
                    gap_tolerance=args.gap_tolerance,
                    merge_distance=args.merge_distance,
                    n_workers=max(1, args.threads // 2))
                null_results_by_depth[depth] = nr
                logging.info(f"  Depth {depth} null: {time.time() - t1:.1f}s")

    # ================================================================
    # Phase 4: Variant Testing
    # ================================================================
    variant_results = None
    if (tgt_vidx is not None and null_results_primary is not None
            and ground_truth_nc is not None):
        variant_results = variant_effect_test(
            rd, wt_idx, tgt_vidx, ground_truth_nc, null_results_primary,
            prom_s, prom_e,
            min_nuc=args.min_nuc, max_nuc=args.max_nuc,
            random_seed=args.random_seed,
            cluster_threshold_quantile=args.cluster_threshold_quantile,
            absolute_delta_threshold=args.absolute_delta_threshold,
            gap_tolerance=args.gap_tolerance,
            merge_distance=args.merge_distance)

    # ================================================================
    # Phase 5: Filter Optimization
    # ================================================================
    filter_results = {}
    if (not args.skip_filter_optimization and tgt_vidx is not None
            and ground_truth_nc is not None):
        filter_results = filter_optimization(
            rd, wt_idx, tgt_vidx, bin_labels,
            min_nuc_grid, max_nuc_pctiles,
            prom_s, prom_e,
            variant_position=vpos,
            n_null_iterations=args.n_filter_null_iters,
            random_seed=args.random_seed,
            analysis_region=analysis_region,
            cluster_threshold_quantile=args.cluster_threshold_quantile,
            gap_tolerance=args.gap_tolerance,
            merge_distance=args.merge_distance,
            n_workers=args.threads)

    # ================================================================
    # Phase 6: Power Analysis
    # ================================================================
    power_results = {}
    if (not args.skip_power_analysis and tgt_vidx is not None
            and null_results_by_depth and ground_truth_nc is not None):
        power_results = power_analysis(
            rd, wt_idx, tgt_vidx, ground_truth_nc,
            null_results_by_depth, coverage_grid,
            prom_s, prom_e,
            min_nuc=args.min_nuc, max_nuc=args.max_nuc,
            n_resamples=args.n_power_resamples,
            random_seed=args.random_seed,
            variant_position=vpos,
            cluster_threshold_quantile=args.cluster_threshold_quantile,
            gap_tolerance=args.gap_tolerance,
            merge_distance=args.merge_distance)

    # ================================================================
    # Output
    # ================================================================
    write_results_hdf5(
        args.output, parse_stats, ground_truth_nc, chromatin_test,
        null_results_primary, null_results_by_depth, variant_results,
        filter_results, power_results,
        bin_labels, ref_length, ref_name, prom_s, prom_e, args)

    generate_diagnostic_pdf(
        args.pdf, chromatin_test, null_results_primary,
        variant_results, filter_results, power_results,
        bin_labels, ref_length, prom_s, prom_e,
        variant_position=vpos, analysis_region=analysis_region)

    generate_notebook_template(args.notebook, args.output, bin_labels)

    print_summary(chromatin_test, variant_results, power_results, bin_labels)

    elapsed = time.time() - start_time
    logging.info(f"\nTotal runtime: {elapsed:.1f}s ({elapsed/60:.1f}m)")


if __name__ == '__main__':
    main()
